language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t asinghde/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true asinghde/react-test npm test -- --coverage

after_success:
  - docker build -t asinghde/multi-client ./client
  - docker build -t asinghde/multi-worker ./worker
  - docker build -t asinghde/multi-nginx ./nginx
  - docker build -t asinghde/multi-server ./server
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push asinghde/multi-client
  - docker push asinghde/multi-worker
  - docker push asinghde/multi-nginx
  - docker push asinghde/multi-server
  # added comment v2

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-986844748062'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY